
@baseUrl = http://localhost:8080
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Hirai Momo",
    "email": "hirai.momo@netho.dev",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "hirai.momo@netho.dev",
    "password": "123456"
}

###

# @name acreate_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}